const LS_PRODUCTS = {
  "three-statement": {
    name: "Three-Statement Financial Model",
    price: "£149",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "dcf": {
    name: "DCF Valuation Model",
    price: "£149",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "lbo": {
    name: "LBO Model",
    price: "£179",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "merger-model": {
    name: "Merger Model (M&A)",
    price: "£179",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "re-development": {
    name: "Real Estate Development Model",
    price: "£169",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "re-investment": {
    name: "Real Estate Investment Model",
    price: "£169",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "nim-analysis": {
    name: "Net Interest Margin (NIM) Analysis",
    price: "£199",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "portfolio-stress": {
    name: "Portfolio Stress Testing Model",
    price: "£199",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "regulatory-capital": {
    name: "Regulatory Capital Model (Basel III/IV)",
    price: "£199",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "ifrs9-ecl": {
    name: "IFRS 9 ECL Model",
    price: "£199",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "budget-forecast": {
    name: "Budget & Forecast Model",
    price: "£129",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "cashflow": {
    name: "Cash Flow Forecasting Model",
    price: "£129",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "kpi-dashboard": {
    name: "KPI Dashboard",
    price: "£99",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "scenario-analysis": {
    name: "Scenario & Sensitivity Analysis",
    price: "£129",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "startup-financial": {
    name: "Startup Financial Model",
    price: "£129",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "project-finance": {
    name: "Project Finance Model",
    price: "£179",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "credit-analysis": {
    name: "Credit Analysis Model",
    price: "£169",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "cap-table": {
    name: "Cap Table & Equity Model",
    price: "£149",
    buyUrl: "PASTE_LS_URL_HERE",
    freeUrl: "PASTE_LS_FREE_URL_HERE",
    checkoutEmbed: true,
  },
  "full-library": {
    name: "Full Model Library Bundle",
    price: "£1499",
    buyUrl: "PASTE_LS_URL_HERE",
    checkoutEmbed: true,
  },
};

export default LS_PRODUCTS;
